### ISSUE TITLE
Coopon, FSHM & Open Mapping

### ISSUE THREAD

**Issue by lrmodesgh** [KaniyamFoundation/ProjectIdeas#105]
Contributing to OSM maps locally, that too substantially on important amenities and based on other usage is of prime importance now. Give the situation of **enclosure of commons** by private companies for their business, will lead ultimately lead to a reduction in the number of free software or community-owned business due to market monopoly. For ex: Facebook, uber... etc.. and their part on contribution back to OSM is still questionable and being debated lots of instances.

With that understanding, we @coopon, @fshm, & @kaniyam need to work collaboratively. I am very well aware about the discussion history started way back a year. But due to other responsibilities, it has been postponed thus far. With @raguls brother Ranjith we can plan to start mapping first armcharing and field-based contribution constantly. 

This can be spiced up by sharing the skill associated to the tools used by the community and practice : 

1. osm, osmand+
2. josm and id
3. hotosm
4. kobo/odk
5. orange3

all these are connected in practice to train as well as orient the contribution towards something of public importance.

With kamal's advice, we can take up the work seriously from this month on. Already mapathon and other training sessions are being held at fshm, without any interference. This will pave the way for Ranjith to learn and engage in the community as well.

Since he knows better about transport logistics (from this father business), I hope he will be interested in making contributions towards street map.

**Learning Task List**
- [ ] Learning OSM And +
- [ ] Learning Street Complete
- [ ] Learning iD or JOSM
- [ ] Learning contribution management with HOTOSM framework (needs to be instantiated)
- [ ] Learning Offline first paper augmented survey using ODK/KoboToolBox (we have our own instance running now for coopon)
- [ ] Learning Data analysis using Orange3 Toolkit (no need of programming skill, but will be useful)

**ToDo Task List**
- [ ] Select area for mapping (brainstorming and hotosm)
- [ ] Practice using osmand+, street complete, Kobocollect
- [ ] Provide proper identification (ID) to answer unexpected questions during field trip (even when done causually, we faced such issues earlier and consumed lot of time)
- [ ] Practice geotagging, field papers for mapping and organize with local communities (already some villages are identified with such interests)
- [ ] Particular emphasis must be placed on mapping urban space and transportation networks
- [ ] very specific field surveys may be organized on issue basis

**Task for FSHM/Coopon**
- [ ] To analyze street networks for errors using analytical tools (pynamical, osmnx... etc)
- [ ] To instantiate a geoportal overlayed with other open data

**Remuneration plan**
The monthly remuneration/salary provided must meet the basic economic requirement and satisfy the equivalent labor to be spent on the work. Since this involves field surveys often, we must take the fatigue and tiredness into account during remuneration. In addition, shall we offer a certificate for mapper from FSHM & Kaniyam combined ??. 

At coopon we have collectively decided not to offer teaching as service. Even though we are the people basically at FSHM, we will be conscious about what to do with which banner.

**Comment by tshrinivasan** [comment]
Thanks for the nice work plan.

//shall we offer a certificate for mapper from FSHM & Kaniyam combined//

This can be done.

Share more details on how long we can run this, what will be the outcomes of a month, minimum expected outputs, and required funds to support

**Comment by ragulkanth** [comment]
For now we are thinking about doing it on a trial basis for at least 6 months.

To my understanding, within this period of time we can actually map the whole pondicherry by employing one dedicated mapper and few theme based mapathons (may be every month) organised by the mapper itself under the banner of both FSHM and Kaniyam Foundation.

**Remuneration per month to One dedicated mapper**
1. 6,000 INR / per month as basic
2. Other expenses like travel, food etc during the field mapping as accounts submitted every month [to my expectation this may be lesser than 1000 INR/Month] 

For six months the cost may goes around ~40, 000 INR

 **Monthly expected outcomes**
We cannot say anything concrete as monthly outcomes. But the plan is to complete the road networks as first priority and organise mapathon as an exercise in order to complete street names and adding basic amenities (ex: hospitals, clinic, pharmacies, tourist places, restaurants, etc.).
